-- SCRIPT DE IMPLANTAÇÃO DO SISTEMA --

CREATE TABLE T_SIP_DEPARTAMENTO
(
    CD_DEPTO NUMBER(2) NOT NULL,
    NM_DEPTO VARCHAR2(30) NOT NULL
);

ALTER TABLE T_SIP_DEPARTAMENTO
    ADD CONSTRAINT PK_SIP_DEPTO PRIMARY KEY(CD_DEPTO);
    
ALTER TABLE T_SIP_DEPARTAMENTO
    ADD CONSTRAINT UN_SPI_DEPTO_NOME UNIQUE(NM_DPTO);


CREATE TABLE T_SIP_FUNCIONARIO(
    NR_MATRICULA NUMBER(5) NOT NULL,
    NM_FUNCIONARIO VARCHAR2(60) NOT NULL,
    CD_DEPTO NUMBER(2) NOT NULL,
    DT_NASCIMENTO DATE NULL,
    DT_ADMISSAO DATE NOT NULL,
    VL_SALARIO NUMBER(7,2) NOT NULL,
    DS_ENDERECO VARCHAR2(80) NOT NULL
);

ALTER TABLE T_SIP_FUNCIONARIO
    ADD CONSTRAINT PK_SIP_FUNCIONARIO PRIMARY KEY (NR_MATRICULA);
    
ALTER TABLE T_SIP_FUNCIONARIO
    ADD CONSTRAINT CK_SIP_FUN_SALARIO CHECK (VL_SALARIO >=937);
    
-- CHAVE ESTRANGEIRA --

ALTER TABLE T_SIP_FUNCIONARIO
    ADD CONSTRAINT FK_SIP_DEPTO_FUNC FOREIGN KEY (CD_DEPTO)
        REFERENCES T_SIP_DEPARTAMENTO(CD_DEPTO);